package main

type InitalWSResponse struct {
	TotalLayer           int    `json:"TotalLayer"`
	AccelToDecelLimits   int    `json:"accelToDecelLimits"`
	AccelerationLimits   int    `json:"accelerationLimits"`
	AiDetection          int    `json:"aiDetection"`
	AiFirstFloor         int    `json:"aiFirstFloor"`
	AiPausePrint         int    `json:"aiPausePrint"`
	AiSw                 int    `json:"aiSw"`
	AutoLevelResult      string `json:"autoLevelResult"`
	Autohome             string `json:"autohome"`
	AuxiliaryFanPct      int    `json:"auxiliaryFanPct"`
	BedTemp0             string `json:"bedTemp0"`
	BedTemp1             string `json:"bedTemp1"`
	BedTemp2             string `json:"bedTemp2"`
	BedTempAutoPid       int    `json:"bedTempAutoPid"`
	BoxTemp              int    `json:"boxTemp"`
	CaseFanPct           int    `json:"caseFanPct"`
	Connect              int    `json:"connect"`
	CornerVelocityLimits int    `json:"cornerVelocityLimits"`
	CurFeedratePct       int    `json:"curFeedratePct"`
	CurFlowratePct       int    `json:"curFlowratePct"`
	CurPosition          string `json:"curPosition"`
	DProgress            int    `json:"dProgress"`
	DeviceState          int    `json:"deviceState"`
	EnableSelfTest       int    `json:"enableSelfTest"`
	Err                  struct {
		Errcode int `json:"errcode"`
		Key     int `json:"key"`
	} `json:"err"`
	Fan                 int    `json:"fan"`
	FanAuxiliary        int    `json:"fanAuxiliary"`
	FanCase             int    `json:"fanCase"`
	Hostname            string `json:"hostname"`
	Layer               int    `json:"layer"`
	LightSw             int    `json:"lightSw"`
	MaterialDetect      int    `json:"materialDetect"`
	MaterialStatus      int    `json:"materialStatus"`
	MaxBedTemp          int    `json:"maxBedTemp"`
	MaxNozzleTemp       int    `json:"maxNozzleTemp"`
	Model               string `json:"model"`
	ModelFanPct         int    `json:"modelFanPct"`
	ModelVersion        string `json:"modelVersion"`
	NozzleMoveSnapshot  int    `json:"nozzleMoveSnapshot"`
	NozzleTemp          string `json:"nozzleTemp"`
	NozzleTempAutoPid   int    `json:"nozzleTempAutoPid"`
	PowerLoss           int    `json:"powerLoss"`
	PressureAdvance     string `json:"pressureAdvance"`
	PrintFileName       string `json:"printFileName"`
	PrintID             string `json:"printId"`
	PrintJobTime        int    `json:"printJobTime"`
	PrintLeftTime       int    `json:"printLeftTime"`
	PrintProgress       int    `json:"printProgress"`
	PrintStartTime      int    `json:"printStartTime"`
	RealTimeFlow        string `json:"realTimeFlow"`
	RealTimeSpeed       string `json:"realTimeSpeed"`
	RepoPlrStatus       int    `json:"repoPlrStatus"`
	SmoothTime          string `json:"smoothTime"`
	State               int    `json:"state"`
	TargetBedTemp0      int    `json:"targetBedTemp0"`
	TargetBedTemp1      int    `json:"targetBedTemp1"`
	TargetBedTemp2      int    `json:"targetBedTemp2"`
	TargetNozzleTemp    int    `json:"targetNozzleTemp"`
	TfCard              int    `json:"tfCard"`
	UpgradeStatus       int    `json:"upgradeStatus"`
	UsedMaterialLength  int    `json:"usedMaterialLength"`
	VelocityLimits      int    `json:"velocityLimits"`
	Video               int    `json:"video"`
	Video1              int    `json:"video1"`
	VideoElapse         int    `json:"videoElapse"`
	VideoElapseFrame    int    `json:"videoElapseFrame"`
	VideoElapseInterval int    `json:"videoElapseInterval"`
	WithSelfTest        int    `json:"withSelfTest"`
}