name: Build Matrix

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          # Windows does not support arm64 via Go cross-compilation in Actions runners
          - os: windows-latest
            arch: amd64
          # MacOS runners currently only run on amd64
          - os: macos-latest
            arch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Set GOOS and GOARCH
        run: |
          echo "GOOS=$(echo '${{ matrix.os }}' | awk -F- '{print $1}')" >> $GITHUB_ENV
          echo "GOARCH=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build
        run: |
          mkdir -p dist
          go build -v -o dist/crlancli-${GOOS}-${GOARCH}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crlancli-${{ env.GOOS }}-${{ env.GOARCH }}
          path: dist/crlancli-${{ env.GOOS }}-${{ env.GOARCH }}
