name: Build Matrix

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    name: Build on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            arch: amd64
          - os: ubuntu-latest
            goos: linux
            arch: arm64
          - os: windows-latest
            goos: windows
            arch: amd64
          - os: macos-latest
            goos: darwin
            arch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build
        run: |
          mkdir -p dist
          go build -v -o dist/crlancli-${{ matrix.goos }}-${{ matrix.arch }} ./...
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crlancli-${{ matrix.goos }}-${{ matrix.arch }}
          path: dist/crlancli-${{ matrix.goos }}-${{ matrix.arch }}
